[project]
name = "UNKNOWN"
version = "0.0.0"
dependencies = [
	"nibabel==5.1.0",
	"scikit-image==0.21.0",
	"trimesh==3.22.3",
]

[project.optional-dependencies]
dev = [
	"black==23.7.0",
	"mypy==1.4.1",
	"ruff==0.0.279",
	"ssort==0.11.6",
]
