[project]
name = "UNKNOWN"
version = "0.0.0"
dependencies = [
	"nibabel==5.1.0",
	"scikit-image==0.21.0",
	"trimesh==3.23.5",
]

[project.optional-dependencies]
dev = [
	"black==23.9.1",
	"djlint==1.34.0",
	"mypy==1.5.1",
	"ruff==0.0.291",
	"ssort==0.11.6",
]
