[project]
name = "UNKNOWN"
version = "0.0.0"
dependencies = [
	"nibabel==5.1.0",
	"scikit-image==0.21.0",
	"trimesh==3.23.5",
]

[project.optional-dependencies]
dev = [
	"black==23.7.0",
	"djlint==1.32.1",
	"mypy==1.5.1",
	"ruff==0.0.286",
	"ssort==0.11.6",
]
