[project]
name = "UNKNOWN"
version = "0.0.0"
dependencies = [
	"nibabel==5.0.0",
	"scikit-image==0.19.3",
	"trimesh==3.18.3",
]

[project.optional-dependencies]
dev = [
	"mypy==1.0.1",
	"ruff==0.0.253",
]
