[project]
name = "UNKNOWN"
version = "0.0.0"
dependencies = [
	"nibabel==4.0.2",
	"scikit-image==0.19.3",
	"trimesh==3.17.1",
]

[project.optional-dependencies]
dev = ["ruff==0.0.205"]

[tool.ruff]
select = ["A", "C", "E", "ERA", "F", "I", "ICN", "N", "PD", "RET", "SIM", "T20", "TID", "UP", "W"]
ignore = ["C901", "E501", "PD013"]
fix = true
