on: [push, pull_request]

jobs:
  make:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Check code and build
        run: |
          cd docs/ && make clean check all && cd ..
          cd python/ && make clean check all && cd ..
      - uses: actions/upload-artifact@v3
        with:
          name: convert-nifti-to-glb
          path: python/tmp/dist/main
  make-windows:
    runs-on: windows-2022
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Check code and build
        run: |
          stop-service *docker*
          dockerd --experimental &
          cd docs/ && make clean check all && cd ..
          cd python/ && make clean check all && cd ..
      - uses: actions/upload-artifact@v3
        with:
          name: convert-nifti-to-glb
          path: python/tmp/dist/main
