on: [push, pull_request]

jobs:
  make:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Check code and build
        run: |
          cd docs/ && make clean check all && cd ..
          cd python/ && make clean check all && cd ..
      - uses: actions/upload-artifact@v3
        with:
          name: convert-nifti-to-glb-linux
          path: python/tmp/dist/convert-nifti-to-glb
  make-windows:
    runs-on: windows-2022
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Check code and build
        run: |
          cd python/ && python3 -m pip install --upgrade pip && python3 -m pip install .[dev] && python3 main.py && cd ..
      - uses: actions/upload-artifact@v3
        with:
          name: convert-nifti-to-glb-windows
          path: python/tmp/dist/convert-nifti-to-glb.exe
  release:
    needs: [make, make-windows]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: |
            convert-nifti-to-glb-linux
            convert-nifti-to-glb-windows
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: |
            convert-nifti-to-glb-linux
            convert-nifti-to-glb-windows
      - uses: dev-drprasad/delete-older-releases@v0.3.2
        with:
          keep_latest: 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
