on: [push, pull_request]

jobs:
  make:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Check code and build
        run: |
          cd docs/ && make clean check all && cd ..
          cd python/ && make clean check all && cd ..
      - name: Create artifact and upload
        run: |
          cd python/ && touch main.py && make STAGING=1 cmd="pyinstaller --specpath tmp/spec --distpath tmp/dist --workpath tmp/build --onefile --windowed main.py"
      - uses: actions/upload-artifact@v3
        with:
          name: convert-nifti-to-glb
          path: python/tmp/dist/main
